package main

//
//	a distributed grep application "plugin" for MapReduce
//
//	go build -buildmode=plugin grep.go
//

import (
	"log"
	"os"
	"regexp"
	"io"
	"6.5840/mr"
)

// The map function is called once for each file of input.
// function to match lines 
func Map(filename string, contents string) []mr.KeyValue {
	// use content in pattern.txt to build regex to find match strings in input contents
	ifilename := "pattern.txt"
	ifile, err := os.Open(ifilename)
	if err != nil {
		log.Fatalf("fail to open pattern.txt")
	}
	
	pat, err := io.ReadAll(ifile)
	if err != nil {
		log.Fatalf("fail to read pattern.txt")
	}

	re := regexp.MustCompile(string(pat))
	matchs := re.FindAllString(contents, -1)
	
	kva := []mr.KeyValue{}
	for _, m := range matchs {
		kv := mr.KeyValue{"", m}
		kva = append(kva, kv)
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	var res string
	for _, value := range values {
		res += value + "\n"
	}
	return res
}